# https://probot.github.io/apps/stale/
---
daysUntilStale: 30
daysUntilClose: 3
onlyLabels: []
exemptLabels:
exemptProjects: false
exemptMilestones: false
exemptAssignees: false
staleLabel: "status: stale"
markComment: >
  This issue has been automatically marked as stale because it has not had
  any recent activity. It will be closed if no further activity occurs.
limitPerRun: 30
only: issues
issues:
  exemptLabels:
    - "status: confirmed"
    - "status: on-hold"
