---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-merge-conflict
      - id: detect-private-key
      - id: no-commit-to-branch
        args: ["--branch", "dev"]
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 39d9ac5938dadb73df0564a45f163e25ff9fa6e2  # frozen: v0.16.1
    hooks:
      - id: ruff-check
        files: "(src|scripts|docs)/"
      - id: ruff-format
        files: "(src|scripts|docs)/"
        args: ["--check"]

  - repo: https://github.com/astral-sh/ty-pre-commit
    rev: ac85803d0443afba1e0700690366fd2d39e02580  # frozen: v0.0.65
    hooks:
      - id: ty

  - repo: https://github.com/adrienverge/yamllint
    rev: cba56bcde1fdd01c1deb3f945e69764c291a6530  # frozen: v1.38.0
    hooks:
      - id: yamllint
        args: ["--strict"]
