---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-merge-conflict
      - id: detect-private-key
      - id: no-commit-to-branch
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 87928e6d6761a4a6d22250e1fee5601b3998086e  # frozen: 26.5.1
    hooks:
      - id: black
        files: "(src|scripts|docs)/"

  - repo: https://github.com/pycqa/isort
    rev: 7f321d375f31a2f03833bc9a548e8783f2b5c420  # frozen: 9.0.0b1
    hooks:
      - id: isort

  - repo: https://github.com/pycqa/flake8
    rev: d93590f5be797aabb60e3b09f2f52dddb02f349f  # frozen: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies: ["Flake8-pyproject==1.2.4"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 41e691678310dfd3833f7ab4e180ddb014310356  # frozen: v2.3.0
    hooks:
      - id: mypy
        files: "(src|scripts)/"

  - repo: https://github.com/adrienverge/yamllint
    rev: cba56bcde1fdd01c1deb3f945e69764c291a6530  # frozen: v1.38.0
    hooks:
      - id: yamllint
        args: ["--strict"]
