---
name: Issue cleanup

on:
  issues:
    types: [closed]

jobs:
  lock-issue:
    runs-on: ubuntu-latest
    name: Lock issue
    steps:
      - name: Lock closed issues
        uses: dessant/lock-threads@v2.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-lock-inactive-days: 0
          issue-lock-comment: >
            Locking this issue.
            [Open a new issue](https://github.com/TomerFi/aioswitcher/issues/new/choose).
          process-only: issues
