---
name: Milestone cleanup

on:
  issues:
    types: [deleted, closed, milestoned, demilestoned]
  pull_request:
    types: [closed, milestoned, demilestoned]

jobs:
  close-finished:
    runs-on: ubuntu-latest
    name: Close finished milestones
    steps:
      - name: Close finished milestones
        uses: instantish/milestone-closer@v1.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
