---
name: Pages Deploy

on:
  workflow_dispatch:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{github.ref}}
  cancel-in-progress: true

env:
  MAIN_PY_VER: "3.14"

jobs:
  deploy-pages:
    runs-on: ubuntu-latest
    environment: github-pages
    permissions:
      pages: write
      contents: write
    name: Build documentation site and deploy to GH-Pages
    steps:
      - name: Checkout sources
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          ref: ${{ github.ref }}
          persist-credentials: false

      - name: Setup uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d  # v10.0.1
        with:
          python-version: ${{ env.MAIN_PY_VER }}
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Build documentation site
        run: uv sync --locked --group docs && uv run --locked mkdocs build --strict

      - name: Deploy to GH-Pages
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453  # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          cname: aioswitcher.figenblat.com
          commit_message: 'docs: deployed documentation site '
