---
name: Pages Deploy

on:
  release:
    types: [published]

jobs:
  deploy-pages:
    runs-on: ubuntu-latest
    environment: github-pages
    name: Build documentation site and deploy to GH-Pages
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2.4.0
        with:
          ref: ${{ github.ref }}

      - name: Setup Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Cache pip repository
        uses: actions/cache@v2.1.7
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Prepare python environment
        run: |
          pip install -rrequirements.txt
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true

      - name: Cache poetry virtual environment
        uses: actions/cache@v2.1.7
        with:
          path: .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Build documenation site
        run: |
          poe install_docs
          poe sphinx_clean_build

      - name: Deploy to GH-Pages
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docsbuild
          cname: aioswitcher.tomfi.info
          commit_message: 'docs: deployed documentation site '
