---
name: Pull request documentation

on: pull_request

jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    name: Verify doc files
    steps:
      - name: Source checkout
        uses: actions/checkout@v2.3.4

      - name: Lint markdown files
        uses: prologic/action-markdownlint@v0.1.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: error

      - name: Check for spelling mistakes
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          locale: "US"
          reporter: github-pr-check
          level: error

      - name: Check links in markdown files
        uses: urlstechie/urlchecker-action@0.2.3
        with:
          file_types: .md,.py,.rst
          force_pass: false
