---
name: Stage

on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - src/**
      - tests/**
      - pyproject.toml
      - requirements.txt

concurrency:
  group: ${{workflow}}-${{github.ref}}
  cancel-in-progress: true

env:
  MAIN_PY_VER: "3.13"

jobs:
  test:
    runs-on: ubuntu-latest
    environment: staging
    name: Stage project
    steps:
      - name: Checkout sources
        uses: 3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false

      - name: Setup timezone
        uses: 040202c2ecba2d55edb016acf01bbeb42261dfc0  # v2.0.0
        with:
          timezone: Asia/Jerusalem

      - name: Set up Python
        uses: 5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
        with:
          python-version: ${{ env.MAIN_PY_VER }}

      - name: Cache pip repository
        uses: 55cc8345863c7cc4c66a329aec7e433d2d1c52a9  # v6.1.0
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-${{ env.MAIN_PY_VER }}

      - name: Prepare python environment
        run: |
          pip install -r requirements.txt
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true

      - name: Cache poetry virtual environment
        uses: 55cc8345863c7cc4c66a329aec7e433d2d1c52a9  # v6.1.0
        with:
          path: .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/pyproject.toml') }}-${{ env.MAIN_PY_VER }}

      - name: Install, test with coverage report, and build
        run: |
          poetry lock
          poetry install --no-interaction
          poetry run poe test_rep
          poetry build

      - name: Push to CodeCov
        uses: a99c28d3f0da835de33ff2feb2e15691c7b9641f  # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          fail_ci_if_error: true
