---
name: Stage

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  stage:
    runs-on: ubuntu-latest
    environment: staging
    name: Stage project
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2.4.0

      - name: Setup timezone
        uses: zcong1993/setup-timezone@v1.1.2
        with:
          timezone: Asia/Jerusalem

      - name: Setup Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Cache pip repository
        uses: actions/cache@v2.1.7
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Prepare python environment
        run: |
          pip install -rrequirements.txt
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true

      - name: Cache poetry virtual environment
        uses: actions/cache@v2.1.7
        with:
          path: .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Install, test with coverage report, and build
        run: |
          poe install_all
          poe test_rep
          poe build

      - name: Push to CodeCov
        uses: codecov/codecov-action@v2.1.0
        with:
          files: coverage.xml
          fail_ci_if_error: true
